site_name: AWS Study
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: indigo 
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: black
      accent: indigo

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ArcoKim
    - icon: fontawesome/solid/blog
      link: https://arcozz.tistory.com
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kimjeongtae

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

copyright: |
  &copy; 2024 <a href="https://github.com/arcokim"  target="_blank" rel="noopener">Arco Kim</a>